import ToggleColor from "./ToggleColor";
import "./TogglePallate.css";

export default function TogglePallate(props) {
  return (
    <div className="font-color">
      <div>
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"BLACK"}
          bgColor={"black"}
          active={props.activeStatus.has("BLACK")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"GRAY"}
          bgColor={"gray"}
          active={props.activeStatus.has("GRAY")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"WHITE"}
          bgColor={"white"}
          active={props.activeStatus.has("WHITE")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"RED"}
          bgColor={"red"}
          active={props.activeStatus.has("RED")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"CRIMSON"}
          bgColor={"#c90c52"}
          active={props.activeStatus.has("CRIMSON")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"deepORANGE"}
          bgColor={"#f2680c"}
          active={props.activeStatus.has("deepORANGE")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"ORANGE"}
          bgColor={"orange"}
          active={props.activeStatus.has("ORANGE")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"BLUE"}
          bgColor={"blue"}
          active={props.activeStatus.has("BLUE")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"DODGER-BLUE"}
          bgColor={"dodgerblue"}
          active={props.activeStatus.has("DODGER-BLUE")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"GREEN"}
          bgColor={"darkgreen"}
          active={props.activeStatus.has("GREEN")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"FOREST-GREEN"}
          bgColor={"forestgreen"}
          active={props.activeStatus.has("FOREST-GREEN")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"LIGHT-GREEN"}
          bgColor={"#19e679"}
          active={props.activeStatus.has("LIGHT-GREEN")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"NEON"}
          bgColor={"#07ede9"}
          active={props.activeStatus.has("NEON")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"YELLOW"}
          bgColor={"yellow"}
          active={props.activeStatus.has("YELLOW")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"PINK"}
          bgColor={"deeppink"}
          active={props.activeStatus.has("PINK")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"PURPLE"}
          bgColor={"#be04beff"}
          active={props.activeStatus.has("PURPLE")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"voilet"}
          bgColor={"#680cad"}
          active={props.activeStatus.has("voilet")}
        />
        <ToggleColor
          handleToggleInlineStyles={props.handleToggleInlineStyles}
          cmd={"BROWN"}
          bgColor={"#591713"}
          active={props.activeStatus.has("BROWN")}
        />
      </div>
      <p
        style={{
          display: "flex",
          alignItems: "flex-end",
          justifyContent: "center",
          cursor: "default",
        }}
      >
        Color Pallete
      </p>
    </div>
  );
}
